name: Flatpak CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ${{ matrix.target.runner }}
    permissions:
      contents: read
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        target:
          - id: flatpak-x86_64
            arch: x86_64
            runner: ubuntu-24.04
          - id: flatpak-aarch64
            arch: aarch64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.pojtinger.felicitas.Sessions.${{ matrix.target.arch }}.flatpak
          manifest-path: com.pojtinger.felicitas.Sessions.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.target.arch }}
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.id }}
          path: "*.flatpak"

  publish-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download output
        uses: actions/download-artifact@v4
        with:
          path: /tmp/out
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Publish pre-release to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.extract_branch.outputs.branch }}
          prerelease: true
          files: |
            /tmp/out/*/*
      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            /tmp/out/*/*
